version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: todos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  # TODO
  # api:
  #   build: .
  #   container_name: api-container
  #   restart: always
  #   depends_on:
  #     - mongo
  #   environment:
  #     PORT: 3005
  #   ports:
  #     - 3005:3005

  app:
    build: .
    container_name: app-container
    restart: always
    depends_on:
      # - api
      - mongo
    environment:
      PORT: 3000
    ports:
      - 3000:3000

volumes:
  mongo-data:
